ALTER TABLE public.foods DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.food_nutrition DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_preferences DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.meal_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.meal_history_pairings DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_dismissals DISABLE ROW LEVEL SECURITY;
